/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BulletinEntity;
import org.openapitools.client.model.PermissionsDTO;
import org.openapitools.client.model.PositionDTO;
import org.openapitools.client.model.ProcessGroupDTO;
import org.openapitools.client.model.ProcessGroupStatusDTO;
import org.openapitools.client.model.RevisionDTO;
import org.openapitools.client.model.VersionedFlowSnapshot;

/**
 * ProcessGroupEntity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-19T16:10:34.866069300-08:00[America/Los_Angeles]")
public class ProcessGroupEntity {
  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private RevisionDTO revision;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private PositionDTO position;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private PermissionsDTO permissions;

  public static final String SERIALIZED_NAME_BULLETINS = "bulletins";
  @SerializedName(SERIALIZED_NAME_BULLETINS)
  private List<BulletinEntity> bulletins = null;

  public static final String SERIALIZED_NAME_COMPONENT = "component";
  @SerializedName(SERIALIZED_NAME_COMPONENT)
  private ProcessGroupDTO component;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ProcessGroupStatusDTO status;

  public static final String SERIALIZED_NAME_VERSIONED_FLOW_SNAPSHOT = "versionedFlowSnapshot";
  @SerializedName(SERIALIZED_NAME_VERSIONED_FLOW_SNAPSHOT)
  private VersionedFlowSnapshot versionedFlowSnapshot;

  public static final String SERIALIZED_NAME_RUNNING_COUNT = "runningCount";
  @SerializedName(SERIALIZED_NAME_RUNNING_COUNT)
  private Integer runningCount;

  public static final String SERIALIZED_NAME_STOPPED_COUNT = "stoppedCount";
  @SerializedName(SERIALIZED_NAME_STOPPED_COUNT)
  private Integer stoppedCount;

  public static final String SERIALIZED_NAME_INVALID_COUNT = "invalidCount";
  @SerializedName(SERIALIZED_NAME_INVALID_COUNT)
  private Integer invalidCount;

  public static final String SERIALIZED_NAME_DISABLED_COUNT = "disabledCount";
  @SerializedName(SERIALIZED_NAME_DISABLED_COUNT)
  private Integer disabledCount;

  public static final String SERIALIZED_NAME_ACTIVE_REMOTE_PORT_COUNT = "activeRemotePortCount";
  @SerializedName(SERIALIZED_NAME_ACTIVE_REMOTE_PORT_COUNT)
  private Integer activeRemotePortCount;

  public static final String SERIALIZED_NAME_INACTIVE_REMOTE_PORT_COUNT = "inactiveRemotePortCount";
  @SerializedName(SERIALIZED_NAME_INACTIVE_REMOTE_PORT_COUNT)
  private Integer inactiveRemotePortCount;

  /**
   * The current state of the Process Group, as it relates to the Versioned Flow
   */
  @JsonAdapter(VersionedFlowStateEnum.Adapter.class)
  public enum VersionedFlowStateEnum {
    LOCALLY_MODIFIED_DESCENDANT("LOCALLY_MODIFIED_DESCENDANT"),
    
    LOCALLY_MODIFIED("LOCALLY_MODIFIED"),
    
    STALE("STALE"),
    
    LOCALLY_MODIFIED_AND_STALE("LOCALLY_MODIFIED_AND_STALE"),
    
    UP_TO_DATE("UP_TO_DATE");

    private String value;

    VersionedFlowStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VersionedFlowStateEnum fromValue(String value) {
      for (VersionedFlowStateEnum b : VersionedFlowStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<VersionedFlowStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VersionedFlowStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VersionedFlowStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VersionedFlowStateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_VERSIONED_FLOW_STATE = "versionedFlowState";
  @SerializedName(SERIALIZED_NAME_VERSIONED_FLOW_STATE)
  private VersionedFlowStateEnum versionedFlowState;

  public static final String SERIALIZED_NAME_UP_TO_DATE_COUNT = "upToDateCount";
  @SerializedName(SERIALIZED_NAME_UP_TO_DATE_COUNT)
  private Integer upToDateCount;

  public static final String SERIALIZED_NAME_LOCALLY_MODIFIED_COUNT = "locallyModifiedCount";
  @SerializedName(SERIALIZED_NAME_LOCALLY_MODIFIED_COUNT)
  private Integer locallyModifiedCount;

  public static final String SERIALIZED_NAME_STALE_COUNT = "staleCount";
  @SerializedName(SERIALIZED_NAME_STALE_COUNT)
  private Integer staleCount;

  public static final String SERIALIZED_NAME_LOCALLY_MODIFIED_AND_STALE_COUNT = "locallyModifiedAndStaleCount";
  @SerializedName(SERIALIZED_NAME_LOCALLY_MODIFIED_AND_STALE_COUNT)
  private Integer locallyModifiedAndStaleCount;

  public static final String SERIALIZED_NAME_SYNC_FAILURE_COUNT = "syncFailureCount";
  @SerializedName(SERIALIZED_NAME_SYNC_FAILURE_COUNT)
  private Integer syncFailureCount;

  public static final String SERIALIZED_NAME_INPUT_PORT_COUNT = "inputPortCount";
  @SerializedName(SERIALIZED_NAME_INPUT_PORT_COUNT)
  private Integer inputPortCount;

  public static final String SERIALIZED_NAME_OUTPUT_PORT_COUNT = "outputPortCount";
  @SerializedName(SERIALIZED_NAME_OUTPUT_PORT_COUNT)
  private Integer outputPortCount;


  public ProcessGroupEntity revision(RevisionDTO revision) {
    
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RevisionDTO getRevision() {
    return revision;
  }


  public void setRevision(RevisionDTO revision) {
    this.revision = revision;
  }


  public ProcessGroupEntity id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of the component.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the component.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ProcessGroupEntity uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * The URI for futures requests to the component.
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URI for futures requests to the component.")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }


  public ProcessGroupEntity position(PositionDTO position) {
    
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PositionDTO getPosition() {
    return position;
  }


  public void setPosition(PositionDTO position) {
    this.position = position;
  }


  public ProcessGroupEntity permissions(PermissionsDTO permissions) {
    
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PermissionsDTO getPermissions() {
    return permissions;
  }


  public void setPermissions(PermissionsDTO permissions) {
    this.permissions = permissions;
  }


  public ProcessGroupEntity bulletins(List<BulletinEntity> bulletins) {
    
    this.bulletins = bulletins;
    return this;
  }

  public ProcessGroupEntity addBulletinsItem(BulletinEntity bulletinsItem) {
    if (this.bulletins == null) {
      this.bulletins = new ArrayList<BulletinEntity>();
    }
    this.bulletins.add(bulletinsItem);
    return this;
  }

   /**
   * The bulletins for this component.
   * @return bulletins
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The bulletins for this component.")

  public List<BulletinEntity> getBulletins() {
    return bulletins;
  }


  public void setBulletins(List<BulletinEntity> bulletins) {
    this.bulletins = bulletins;
  }


  public ProcessGroupEntity component(ProcessGroupDTO component) {
    
    this.component = component;
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProcessGroupDTO getComponent() {
    return component;
  }


  public void setComponent(ProcessGroupDTO component) {
    this.component = component;
  }


  public ProcessGroupEntity status(ProcessGroupStatusDTO status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProcessGroupStatusDTO getStatus() {
    return status;
  }


  public void setStatus(ProcessGroupStatusDTO status) {
    this.status = status;
  }


  public ProcessGroupEntity versionedFlowSnapshot(VersionedFlowSnapshot versionedFlowSnapshot) {
    
    this.versionedFlowSnapshot = versionedFlowSnapshot;
    return this;
  }

   /**
   * Get versionedFlowSnapshot
   * @return versionedFlowSnapshot
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VersionedFlowSnapshot getVersionedFlowSnapshot() {
    return versionedFlowSnapshot;
  }


  public void setVersionedFlowSnapshot(VersionedFlowSnapshot versionedFlowSnapshot) {
    this.versionedFlowSnapshot = versionedFlowSnapshot;
  }


  public ProcessGroupEntity runningCount(Integer runningCount) {
    
    this.runningCount = runningCount;
    return this;
  }

   /**
   * The number of running components in this process group.
   * @return runningCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of running components in this process group.")

  public Integer getRunningCount() {
    return runningCount;
  }


  public void setRunningCount(Integer runningCount) {
    this.runningCount = runningCount;
  }


  public ProcessGroupEntity stoppedCount(Integer stoppedCount) {
    
    this.stoppedCount = stoppedCount;
    return this;
  }

   /**
   * The number of stopped components in the process group.
   * @return stoppedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of stopped components in the process group.")

  public Integer getStoppedCount() {
    return stoppedCount;
  }


  public void setStoppedCount(Integer stoppedCount) {
    this.stoppedCount = stoppedCount;
  }


  public ProcessGroupEntity invalidCount(Integer invalidCount) {
    
    this.invalidCount = invalidCount;
    return this;
  }

   /**
   * The number of invalid components in the process group.
   * @return invalidCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of invalid components in the process group.")

  public Integer getInvalidCount() {
    return invalidCount;
  }


  public void setInvalidCount(Integer invalidCount) {
    this.invalidCount = invalidCount;
  }


  public ProcessGroupEntity disabledCount(Integer disabledCount) {
    
    this.disabledCount = disabledCount;
    return this;
  }

   /**
   * The number of disabled components in the process group.
   * @return disabledCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of disabled components in the process group.")

  public Integer getDisabledCount() {
    return disabledCount;
  }


  public void setDisabledCount(Integer disabledCount) {
    this.disabledCount = disabledCount;
  }


  public ProcessGroupEntity activeRemotePortCount(Integer activeRemotePortCount) {
    
    this.activeRemotePortCount = activeRemotePortCount;
    return this;
  }

   /**
   * The number of active remote ports in the process group.
   * @return activeRemotePortCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of active remote ports in the process group.")

  public Integer getActiveRemotePortCount() {
    return activeRemotePortCount;
  }


  public void setActiveRemotePortCount(Integer activeRemotePortCount) {
    this.activeRemotePortCount = activeRemotePortCount;
  }


  public ProcessGroupEntity inactiveRemotePortCount(Integer inactiveRemotePortCount) {
    
    this.inactiveRemotePortCount = inactiveRemotePortCount;
    return this;
  }

   /**
   * The number of inactive remote ports in the process group.
   * @return inactiveRemotePortCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of inactive remote ports in the process group.")

  public Integer getInactiveRemotePortCount() {
    return inactiveRemotePortCount;
  }


  public void setInactiveRemotePortCount(Integer inactiveRemotePortCount) {
    this.inactiveRemotePortCount = inactiveRemotePortCount;
  }


   /**
   * The current state of the Process Group, as it relates to the Versioned Flow
   * @return versionedFlowState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The current state of the Process Group, as it relates to the Versioned Flow")

  public VersionedFlowStateEnum getVersionedFlowState() {
    return versionedFlowState;
  }




  public ProcessGroupEntity upToDateCount(Integer upToDateCount) {
    
    this.upToDateCount = upToDateCount;
    return this;
  }

   /**
   * The number of up to date versioned process groups in the process group.
   * @return upToDateCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of up to date versioned process groups in the process group.")

  public Integer getUpToDateCount() {
    return upToDateCount;
  }


  public void setUpToDateCount(Integer upToDateCount) {
    this.upToDateCount = upToDateCount;
  }


  public ProcessGroupEntity locallyModifiedCount(Integer locallyModifiedCount) {
    
    this.locallyModifiedCount = locallyModifiedCount;
    return this;
  }

   /**
   * The number of locally modified versioned process groups in the process group.
   * @return locallyModifiedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of locally modified versioned process groups in the process group.")

  public Integer getLocallyModifiedCount() {
    return locallyModifiedCount;
  }


  public void setLocallyModifiedCount(Integer locallyModifiedCount) {
    this.locallyModifiedCount = locallyModifiedCount;
  }


  public ProcessGroupEntity staleCount(Integer staleCount) {
    
    this.staleCount = staleCount;
    return this;
  }

   /**
   * The number of stale versioned process groups in the process group.
   * @return staleCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of stale versioned process groups in the process group.")

  public Integer getStaleCount() {
    return staleCount;
  }


  public void setStaleCount(Integer staleCount) {
    this.staleCount = staleCount;
  }


  public ProcessGroupEntity locallyModifiedAndStaleCount(Integer locallyModifiedAndStaleCount) {
    
    this.locallyModifiedAndStaleCount = locallyModifiedAndStaleCount;
    return this;
  }

   /**
   * The number of locally modified and stale versioned process groups in the process group.
   * @return locallyModifiedAndStaleCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of locally modified and stale versioned process groups in the process group.")

  public Integer getLocallyModifiedAndStaleCount() {
    return locallyModifiedAndStaleCount;
  }


  public void setLocallyModifiedAndStaleCount(Integer locallyModifiedAndStaleCount) {
    this.locallyModifiedAndStaleCount = locallyModifiedAndStaleCount;
  }


  public ProcessGroupEntity syncFailureCount(Integer syncFailureCount) {
    
    this.syncFailureCount = syncFailureCount;
    return this;
  }

   /**
   * The number of versioned process groups in the process group that are unable to sync to a registry.
   * @return syncFailureCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of versioned process groups in the process group that are unable to sync to a registry.")

  public Integer getSyncFailureCount() {
    return syncFailureCount;
  }


  public void setSyncFailureCount(Integer syncFailureCount) {
    this.syncFailureCount = syncFailureCount;
  }


  public ProcessGroupEntity inputPortCount(Integer inputPortCount) {
    
    this.inputPortCount = inputPortCount;
    return this;
  }

   /**
   * The number of input ports in the process group.
   * @return inputPortCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of input ports in the process group.")

  public Integer getInputPortCount() {
    return inputPortCount;
  }


  public void setInputPortCount(Integer inputPortCount) {
    this.inputPortCount = inputPortCount;
  }


  public ProcessGroupEntity outputPortCount(Integer outputPortCount) {
    
    this.outputPortCount = outputPortCount;
    return this;
  }

   /**
   * The number of output ports in the process group.
   * @return outputPortCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of output ports in the process group.")

  public Integer getOutputPortCount() {
    return outputPortCount;
  }


  public void setOutputPortCount(Integer outputPortCount) {
    this.outputPortCount = outputPortCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessGroupEntity processGroupEntity = (ProcessGroupEntity) o;
    return Objects.equals(this.revision, processGroupEntity.revision) &&
        Objects.equals(this.id, processGroupEntity.id) &&
        Objects.equals(this.uri, processGroupEntity.uri) &&
        Objects.equals(this.position, processGroupEntity.position) &&
        Objects.equals(this.permissions, processGroupEntity.permissions) &&
        Objects.equals(this.bulletins, processGroupEntity.bulletins) &&
        Objects.equals(this.component, processGroupEntity.component) &&
        Objects.equals(this.status, processGroupEntity.status) &&
        Objects.equals(this.versionedFlowSnapshot, processGroupEntity.versionedFlowSnapshot) &&
        Objects.equals(this.runningCount, processGroupEntity.runningCount) &&
        Objects.equals(this.stoppedCount, processGroupEntity.stoppedCount) &&
        Objects.equals(this.invalidCount, processGroupEntity.invalidCount) &&
        Objects.equals(this.disabledCount, processGroupEntity.disabledCount) &&
        Objects.equals(this.activeRemotePortCount, processGroupEntity.activeRemotePortCount) &&
        Objects.equals(this.inactiveRemotePortCount, processGroupEntity.inactiveRemotePortCount) &&
        Objects.equals(this.versionedFlowState, processGroupEntity.versionedFlowState) &&
        Objects.equals(this.upToDateCount, processGroupEntity.upToDateCount) &&
        Objects.equals(this.locallyModifiedCount, processGroupEntity.locallyModifiedCount) &&
        Objects.equals(this.staleCount, processGroupEntity.staleCount) &&
        Objects.equals(this.locallyModifiedAndStaleCount, processGroupEntity.locallyModifiedAndStaleCount) &&
        Objects.equals(this.syncFailureCount, processGroupEntity.syncFailureCount) &&
        Objects.equals(this.inputPortCount, processGroupEntity.inputPortCount) &&
        Objects.equals(this.outputPortCount, processGroupEntity.outputPortCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(revision, id, uri, position, permissions, bulletins, component, status, versionedFlowSnapshot, runningCount, stoppedCount, invalidCount, disabledCount, activeRemotePortCount, inactiveRemotePortCount, versionedFlowState, upToDateCount, locallyModifiedCount, staleCount, locallyModifiedAndStaleCount, syncFailureCount, inputPortCount, outputPortCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessGroupEntity {\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    bulletins: ").append(toIndentedString(bulletins)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    versionedFlowSnapshot: ").append(toIndentedString(versionedFlowSnapshot)).append("\n");
    sb.append("    runningCount: ").append(toIndentedString(runningCount)).append("\n");
    sb.append("    stoppedCount: ").append(toIndentedString(stoppedCount)).append("\n");
    sb.append("    invalidCount: ").append(toIndentedString(invalidCount)).append("\n");
    sb.append("    disabledCount: ").append(toIndentedString(disabledCount)).append("\n");
    sb.append("    activeRemotePortCount: ").append(toIndentedString(activeRemotePortCount)).append("\n");
    sb.append("    inactiveRemotePortCount: ").append(toIndentedString(inactiveRemotePortCount)).append("\n");
    sb.append("    versionedFlowState: ").append(toIndentedString(versionedFlowState)).append("\n");
    sb.append("    upToDateCount: ").append(toIndentedString(upToDateCount)).append("\n");
    sb.append("    locallyModifiedCount: ").append(toIndentedString(locallyModifiedCount)).append("\n");
    sb.append("    staleCount: ").append(toIndentedString(staleCount)).append("\n");
    sb.append("    locallyModifiedAndStaleCount: ").append(toIndentedString(locallyModifiedAndStaleCount)).append("\n");
    sb.append("    syncFailureCount: ").append(toIndentedString(syncFailureCount)).append("\n");
    sb.append("    inputPortCount: ").append(toIndentedString(inputPortCount)).append("\n");
    sb.append("    outputPortCount: ").append(toIndentedString(outputPortCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

