/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VariableRegistryUpdateStepDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-19T16:10:34.866069300-08:00[America/Los_Angeles]")
public class VariableRegistryUpdateStepDTO {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_COMPLETE = "complete";
  @SerializedName(SERIALIZED_NAME_COMPLETE)
  private Boolean complete;

  public static final String SERIALIZED_NAME_FAILURE_REASON = "failureReason";
  @SerializedName(SERIALIZED_NAME_FAILURE_REASON)
  private String failureReason;


   /**
   * Explanation of what happens in this step
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Explanation of what happens in this step")

  public String getDescription() {
    return description;
  }




   /**
   * Whether or not this step has completed
   * @return complete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not this step has completed")

  public Boolean getComplete() {
    return complete;
  }




   /**
   * An explanation of why this step failed, or null if this step did not fail
   * @return failureReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An explanation of why this step failed, or null if this step did not fail")

  public String getFailureReason() {
    return failureReason;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryUpdateStepDTO variableRegistryUpdateStepDTO = (VariableRegistryUpdateStepDTO) o;
    return Objects.equals(this.description, variableRegistryUpdateStepDTO.description) &&
        Objects.equals(this.complete, variableRegistryUpdateStepDTO.complete) &&
        Objects.equals(this.failureReason, variableRegistryUpdateStepDTO.failureReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, complete, failureReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryUpdateStepDTO {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

