/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.client.model.AffectedComponentEntity;

/**
 * VariableDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-19T16:10:34.866069300-08:00[America/Los_Angeles]")
public class VariableDTO {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_PROCESS_GROUP_ID = "processGroupId";
  @SerializedName(SERIALIZED_NAME_PROCESS_GROUP_ID)
  private String processGroupId;

  public static final String SERIALIZED_NAME_AFFECTED_COMPONENTS = "affectedComponents";
  @SerializedName(SERIALIZED_NAME_AFFECTED_COMPONENTS)
  private Set<AffectedComponentEntity> affectedComponents = null;


  public VariableDTO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the variable
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the variable")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VariableDTO value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * The value of the variable
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value of the variable")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


   /**
   * The ID of the Process Group where this Variable is defined
   * @return processGroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the Process Group where this Variable is defined")

  public String getProcessGroupId() {
    return processGroupId;
  }




   /**
   * A set of all components that will be affected if the value of this variable is changed
   * @return affectedComponents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of all components that will be affected if the value of this variable is changed")

  public Set<AffectedComponentEntity> getAffectedComponents() {
    return affectedComponents;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableDTO variableDTO = (VariableDTO) o;
    return Objects.equals(this.name, variableDTO.name) &&
        Objects.equals(this.value, variableDTO.value) &&
        Objects.equals(this.processGroupId, variableDTO.processGroupId) &&
        Objects.equals(this.affectedComponents, variableDTO.affectedComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, processGroupId, affectedComponents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableDTO {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    processGroupId: ").append(toIndentedString(processGroupId)).append("\n");
    sb.append("    affectedComponents: ").append(toIndentedString(affectedComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

