/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.RevisionDTO;
import org.openapitools.client.model.VariableRegistryUpdateRequestDTO;

/**
 * VariableRegistryUpdateRequestEntity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-19T16:10:34.866069300-08:00[America/Los_Angeles]")
public class VariableRegistryUpdateRequestEntity {
  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private VariableRegistryUpdateRequestDTO request;

  public static final String SERIALIZED_NAME_PROCESS_GROUP_REVISION = "processGroupRevision";
  @SerializedName(SERIALIZED_NAME_PROCESS_GROUP_REVISION)
  private RevisionDTO processGroupRevision;


  public VariableRegistryUpdateRequestEntity request(VariableRegistryUpdateRequestDTO request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VariableRegistryUpdateRequestDTO getRequest() {
    return request;
  }


  public void setRequest(VariableRegistryUpdateRequestDTO request) {
    this.request = request;
  }


  public VariableRegistryUpdateRequestEntity processGroupRevision(RevisionDTO processGroupRevision) {
    
    this.processGroupRevision = processGroupRevision;
    return this;
  }

   /**
   * Get processGroupRevision
   * @return processGroupRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RevisionDTO getProcessGroupRevision() {
    return processGroupRevision;
  }


  public void setProcessGroupRevision(RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryUpdateRequestEntity variableRegistryUpdateRequestEntity = (VariableRegistryUpdateRequestEntity) o;
    return Objects.equals(this.request, variableRegistryUpdateRequestEntity.request) &&
        Objects.equals(this.processGroupRevision, variableRegistryUpdateRequestEntity.processGroupRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, processGroupRevision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryUpdateRequestEntity {\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    processGroupRevision: ").append(toIndentedString(processGroupRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

